// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkxWv1c6C8B0EfMc9Bu0EeXZOFWx9xx6U',
    appId: '1:73878630724:web:e351e2944bb2f14d38a711',
    messagingSenderId: '73878630724',
    projectId: 'iot-project-d5d01',
    authDomain: 'iot-project-d5d01.firebaseapp.com',
    databaseURL: 'https://iot-project-d5d01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-d5d01.appspot.com',
    measurementId: 'G-Z9BRDMPWR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhl9vnd2XzaJ0xFR5LDPyMemDMqN-VB4',
    appId: '1:73878630724:android:71aed09e25e1920138a711',
    messagingSenderId: '73878630724',
    projectId: 'iot-project-d5d01',
    databaseURL: 'https://iot-project-d5d01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-d5d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRNCPNaJyxKu40ul2QegUjYU7BN837--c',
    appId: '1:73878630724:ios:207e424b7085121038a711',
    messagingSenderId: '73878630724',
    projectId: 'iot-project-d5d01',
    databaseURL: 'https://iot-project-d5d01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-d5d01.appspot.com',
    iosClientId: '73878630724-12up1cjvovl1ifkbldmktbsfsmn6inut.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasrancang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRNCPNaJyxKu40ul2QegUjYU7BN837--c',
    appId: '1:73878630724:ios:207e424b7085121038a711',
    messagingSenderId: '73878630724',
    projectId: 'iot-project-d5d01',
    databaseURL: 'https://iot-project-d5d01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-d5d01.appspot.com',
    iosClientId: '73878630724-12up1cjvovl1ifkbldmktbsfsmn6inut.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasrancang',
  );
}
